-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-09-13 11:31:08 CST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AUDITORIA_INSCRIPCION 
    ( 
     ID_AUDITORIA    INTEGER  NOT NULL , 
     ID_INSCRIPCION  INTEGER  NOT NULL , 
     OPERACION       VARCHAR2 (10 CHAR)  NOT NULL , 
     USUARIO_BD      VARCHAR2 (50 CHAR)  NOT NULL , 
     FECHA_OPERACION TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ESTADO_ANTERIOR VARCHAR2 (15 CHAR) , 
     ESTADO_NUEVO    VARCHAR2 (15 CHAR) , 
     DETALLE         VARCHAR2 (500 CHAR) 
    ) 
;

ALTER TABLE AUDITORIA_INSCRIPCION 
    ADD CONSTRAINT CK_AUDITORIA_OPERACION 
    CHECK (OPERACION IN ('INSERT', 'UPDATE', 'DELETE'))
;
ALTER TABLE AUDITORIA_INSCRIPCION 
    ADD CONSTRAINT PK_AUDITORIA_CODIGO PRIMARY KEY ( ID_AUDITORIA ) ;

CREATE TABLE CARRERA 
    ( 
     ID_CARRERA     INTEGER  NOT NULL , 
     CODIGO_CARRERA VARCHAR2 (10 CHAR)  NOT NULL , 
     NOMBRE         VARCHAR2 (100 CHAR)  NOT NULL , 
     ESTADO         VARCHAR2 (10 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CARRERA 
    ADD CONSTRAINT CK_CARRERA_ESTADO 
    CHECK (ESTADO IN ('ACTIVA', 'INACTIVA'))
;
ALTER TABLE CARRERA 
    ADD CONSTRAINT PK_CARRERA_CODIGO PRIMARY KEY ( ID_CARRERA ) ;

ALTER TABLE CARRERA 
    ADD CONSTRAINT UK_CARRERA_CODIGO UNIQUE ( CODIGO_CARRERA ) ;

CREATE TABLE CURSO 
    ( 
     ID_CURSO     INTEGER  NOT NULL , 
     CODIGO_CURSO VARCHAR2 (15 CHAR)  NOT NULL , 
     NOMBRE_CURSO VARCHAR2 (120 CHAR)  NOT NULL , 
     CREDITOS     INTEGER  NOT NULL , 
     ESTADO       VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE CURSO 
    ADD CONSTRAINT CK_CURSO_ESTADO 
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
;


ALTER TABLE CURSO 
    ADD CONSTRAINT CK_CURSO_CREDITOS 
    CHECK (CREDITOS > 0)
;
ALTER TABLE CURSO 
    ADD CONSTRAINT PK_CURSO_CODIGO PRIMARY KEY ( ID_CURSO ) ;

ALTER TABLE CURSO 
    ADD CONSTRAINT UK_CURSO_CODIGO UNIQUE ( CODIGO_CURSO ) ;

CREATE TABLE DOCENTE 
    ( 
     ID_DOCENTE     INTEGER  NOT NULL , 
     CODIGO_DOCENTE VARCHAR2 (20 CHAR)  NOT NULL , 
     NOMBRE         VARCHAR2 (60 CHAR)  NOT NULL , 
     APELLIDO       VARCHAR2 (60 CHAR)  NOT NULL , 
     EMAIL          VARCHAR2 (120 CHAR) , 
     ESTADO         VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE DOCENTE 
    ADD CONSTRAINT CK_DOCENTE_ESTADO 
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
;
ALTER TABLE DOCENTE 
    ADD CONSTRAINT PK_DOCENTE_CODIGO PRIMARY KEY ( ID_DOCENTE ) ;

ALTER TABLE DOCENTE 
    ADD CONSTRAINT UK_DOCENTE_CODIGO UNIQUE ( CODIGO_DOCENTE ) ;

ALTER TABLE DOCENTE 
    ADD CONSTRAINT UK_DOCENTE_EMAIL UNIQUE ( EMAIL ) ;

CREATE TABLE ESTUDIANTE 
    ( 
     ID_ESTUDIANTE INTEGER  NOT NULL , 
     CARNET        VARCHAR2 (20 CHAR)  NOT NULL , 
     NOMBRE        VARCHAR2 (60 CHAR)  NOT NULL , 
     APELLIDO      VARCHAR2 (60 CHAR)  NOT NULL , 
     EMAIL         VARCHAR2 (120 CHAR) , 
     ID_CARRERA    INTEGER  NOT NULL , 
     ESTADO        VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT CK_ESTUDIANTE_ESTADO 
    CHECK (ESTADO IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO'))
;
ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT PK_ESTUDIANTE_CODIGO PRIMARY KEY ( ID_ESTUDIANTE ) ;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT UK_ESTUDIANTE_CARNET UNIQUE ( CARNET ) ;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT UK_ESTUDIANTE_EMAIL UNIQUE ( EMAIL ) ;

CREATE TABLE HORARIO 
    ( 
     ID_HORARIO  INTEGER  NOT NULL , 
     ID_SECCION  INTEGER  NOT NULL , 
     DIA_SEMANA  VARCHAR2 (10 CHAR)  NOT NULL , 
     HORA_INICIO VARCHAR2 (5 CHAR)  NOT NULL , 
     HORA_FIN    VARCHAR2 (5 CHAR)  NOT NULL , 
     AULA        VARCHAR2 (30 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE HORARIO 
    ADD CONSTRAINT CK_HORARIO_DIA 
    CHECK (DIA_SEMANA IN (
    'LUNES',
    'MARTES',
    'MIERCOLES',
    'JUEVES',
    'VIERNES',
    'SABADO'
))
;
ALTER TABLE HORARIO 
    ADD CONSTRAINT PK_HORARIO_CODIGO PRIMARY KEY ( ID_HORARIO ) ;

CREATE TABLE INSCRIPCION 
    ( 
     ID_INSCRIPCION    INTEGER  NOT NULL , 
     ID_ESTUDIANTE     INTEGER  NOT NULL , 
     ID_SECCION        INTEGER  NOT NULL , 
     FECHA_INSCRIPCION TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ESTADO            VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE INSCRIPCION 
    ADD CONSTRAINT CK_INSCRIPCION_ESTADO 
    CHECK (ESTADO IN (
    'ACTIVA',
    'CANCELADA',
    'RECHAZADA'
))
;
ALTER TABLE INSCRIPCION 
    ADD CONSTRAINT PK_INSCRIPCION_CODIGO PRIMARY KEY ( ID_INSCRIPCION ) ;

ALTER TABLE INSCRIPCION 
    ADD CONSTRAINT UK_INSCRIPCION_ESTUDIANTE_SECCION UNIQUE ( ID_ESTUDIANTE , ID_SECCION ) ;

CREATE TABLE PERIODO_ACADEMICO 
    ( 
     ID_PERIODO   INTEGER  NOT NULL , 
     ANIO         INTEGER  NOT NULL , 
     CICLO        INTEGER  NOT NULL , 
     FECHA_INICIO DATE  NOT NULL , 
     FECHA_FIN    DATE  NOT NULL , 
     ESTADO       VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE PERIODO_ACADEMICO 
    ADD CONSTRAINT CK_PERIODO_ACADEMICO_CICLO 
    CHECK (CICLO IN (1,2))
;


ALTER TABLE PERIODO_ACADEMICO 
    ADD CONSTRAINT CK_PERIODO_ACADEMICO_ESTADO 
    CHECK (ESTADO IN ('PLANIFICADO', 'ACTIVO', 'FINALIZADO'))
;


ALTER TABLE PERIODO_ACADEMICO 
    ADD CONSTRAINT CK_PERIODO_FECHAS 
    CHECK (FECHA_FIN > FECHA_INICIO)
;
ALTER TABLE PERIODO_ACADEMICO 
    ADD CONSTRAINT PK_PERIODO_ACADEMICO_CODIGO PRIMARY KEY ( ID_PERIODO ) ;

ALTER TABLE PERIODO_ACADEMICO 
    ADD CONSTRAINT UK_PERIODO_ACADEMICO UNIQUE ( ANIO , CICLO ) ;

CREATE TABLE SECCION 
    ( 
     ID_SECCION      INTEGER  NOT NULL , 
     ID_CURSO        INTEGER  NOT NULL , 
     ID_DOCENTE      INTEGER  NOT NULL , 
     ID_PERIODO      INTEGER  NOT NULL , 
     CODIGO_SECCION  VARCHAR2 (10 CHAR)  NOT NULL , 
     CUPO_MAXIMO     INTEGER  NOT NULL , 
     CUPO_DISPONIBLE INTEGER  NOT NULL , 
     ESTADO          VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SECCION 
    ADD CONSTRAINT CK_SECCION_CUPO_MAX 
    CHECK (CUPO_MAXIMO > 0)
;


ALTER TABLE SECCION 
    ADD CONSTRAINT CK_SECCION_CUPO_DIS 
    CHECK (CUPO_DISPONIBLE >= 0
AND CUPO_DISPONIBLE <= CUPO_MAXIMO)
;


ALTER TABLE SECCION 
    ADD CONSTRAINT CK_SECCION_ESTADO 
    CHECK (ESTADO IN ('ABIERTA', 'CERRADA', 'INACTIVA'))
;
ALTER TABLE SECCION 
    ADD CONSTRAINT PK_SECCION_CODIGO PRIMARY KEY ( ID_SECCION ) ;

CREATE TABLE SOLICITUD_INSCRIPCION 
    ( 
     ID_SOLICITUD      INTEGER  NOT NULL , 
     ID_ESTUDIANTE     INTEGER  NOT NULL , 
     ID_SECCION        INTEGER  NOT NULL , 
     FECHA_SOLICITUD   TIMESTAMP DEFAULT SYSTIMESTAMP  NOT NULL , 
     ESTADO            VARCHAR2 (15 CHAR)  NOT NULL , 
     FECHA_PROCESADA   TIMESTAMP , 
     MENSAJE_RESULTADO VARCHAR2 (250 CHAR) 
    ) 
;

ALTER TABLE SOLICITUD_INSCRIPCION 
    ADD CONSTRAINT CK_SOLICITUD_ESTADO 
    CHECK (ESTADO IN (
            'PENDIENTE',
            'PROCESANDO',
            'PROCESADA',
            'RECHAZADA'
        ))
;
ALTER TABLE SOLICITUD_INSCRIPCION 
    ADD CONSTRAINT PK_SOLICITUD_CODIGO PRIMARY KEY ( ID_SOLICITUD ) ;

ALTER TABLE AUDITORIA_INSCRIPCION 
    ADD CONSTRAINT FK_AUDITORIA_INSCRIPCION FOREIGN KEY 
    ( 
     ID_INSCRIPCION
    ) 
    REFERENCES INSCRIPCION 
    ( 
     ID_INSCRIPCION
    ) 
;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT FK_ESTUDIANTE_CARRERA FOREIGN KEY 
    ( 
     ID_CARRERA
    ) 
    REFERENCES CARRERA 
    ( 
     ID_CARRERA
    ) 
;

ALTER TABLE HORARIO 
    ADD CONSTRAINT FK_HORARIO_SECCION FOREIGN KEY 
    ( 
     ID_SECCION
    ) 
    REFERENCES SECCION 
    ( 
     ID_SECCION
    ) 
;

ALTER TABLE INSCRIPCION 
    ADD CONSTRAINT FK_INSCRIPCION_ESTUDIANTE FOREIGN KEY 
    ( 
     ID_ESTUDIANTE
    ) 
    REFERENCES ESTUDIANTE 
    ( 
     ID_ESTUDIANTE
    ) 
;

ALTER TABLE INSCRIPCION 
    ADD CONSTRAINT FK_INSCRIPCION_SECCION FOREIGN KEY 
    ( 
     ID_SECCION
    ) 
    REFERENCES SECCION 
    ( 
     ID_SECCION
    ) 
;

ALTER TABLE SECCION 
    ADD CONSTRAINT FK_SECCION_CURSO FOREIGN KEY 
    ( 
     ID_CURSO
    ) 
    REFERENCES CURSO 
    ( 
     ID_CURSO
    ) 
;

ALTER TABLE SECCION 
    ADD CONSTRAINT FK_SECCION_DOCENTE FOREIGN KEY 
    ( 
     ID_DOCENTE
    ) 
    REFERENCES DOCENTE 
    ( 
     ID_DOCENTE
    ) 
;

ALTER TABLE SECCION 
    ADD CONSTRAINT FK_SECCION_PERIODO FOREIGN KEY 
    ( 
     ID_PERIODO
    ) 
    REFERENCES PERIODO_ACADEMICO 
    ( 
     ID_PERIODO
    ) 
;

ALTER TABLE SOLICITUD_INSCRIPCION 
    ADD CONSTRAINT FK_SOLICITUD_ESTUDIANTE FOREIGN KEY 
    ( 
     ID_ESTUDIANTE
    ) 
    REFERENCES ESTUDIANTE 
    ( 
     ID_ESTUDIANTE
    ) 
;

ALTER TABLE SOLICITUD_INSCRIPCION 
    ADD CONSTRAINT FK_SOLICITUD_SECCION FOREIGN KEY 
    ( 
     ID_SECCION
    ) 
    REFERENCES SECCION 
    ( 
     ID_SECCION
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             43
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
